# action builds and pushes the satic files to build branch

name: build to branch

on:
  push:
    branches: [ "main" ]

jobs:
  stage_copy:
    runs-on: ubuntu-latest

    steps: 
    - name: get the master branch
      uses: actions/checkout@v4
      with:
        ref: main
    
    - name: commit.sha
      run: echo "${{ github.sha }}" > ./piApi/github.sha.txt

    - name: stage files
      run: |
        mkdir staged
        cp -r ./piApi/* ./staged
  
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ./staged
  
  paste_Push:
    runs-on: ubuntu-latest
    needs: stage_copy
    permissions:
      contents: write

    steps:
    - name: get the builds branch
      uses: actions/checkout@v4
      with:
        ref: builds
    
    - name: get time
      run: echo "date=$(date)" >> "$GITHUB_ENV"
    
    - name: delete old builds
      run: rm -rf $(git ls-files | sed s/"README.md"// | sed s/".gitignore"// | sed s/"LICENSE"//)

    - uses: actions/download-artifact@v4
      with:
        name: ${{ github.sha }}
        path: .
     
    - uses: actions4git/setup-git@v1 
    - run: |
        git add .
        git commit -m 'autopush @[${{ env.date }}]'
        git push
